server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multi_module_architecture?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
logging:
  level:
    com.keveon.architecture: trace
    com.mysql: warn
    org.hibernate: warn
    org.springframework: warn
